version: '2.4'  # view README.md before running if admin db and admin user needed
services:
  ps_utils_dev:
    image: vernonco/ps-utils:dev
    container_name: ps_utils_dev
    environment:
#      - local=true
      - TERM=xterm
      - ENVIRONMENT= # use 1 or production for production environment.  Look for PRODUCTION variable in code.
      - DB_AUTH=youruser
      - DB_PASS=yourpassword
      - DB_HOST=db
      - DB_PORT=3306
      - CONFIG_FILE=config  # or config-4passwords if bringing over previous passwords
      - FLASK_APP="app:app"   # set to run flask fab create-admin (see README.md).
      - FLASK_ENV=development       # comment out to run without debugging
      - GUWORKERS_CONNECTIONS=1001  #needed if FLASK_ENV  is commented out
      - GUWORKERS=4                 #needed if FLASK_ENV  is commented out
      - SERVER_PATH=/app
      - FAB_STATIC_FOLDER=/app/app/static/appbuilder
      - FAB_STATIC_URL_PATH=/appbuilder
      # - RECAPTCHA_PUBLIC_KEY=
      # - RECAPTCHA_PRIVATE_KEY=
      # - SMTP_SERVER=
      # - SMTP_FROM=
      # - SMTP_PORT=          # defaults to 587 if not passed
      # - SMTP_TLS_OR_SSL=    # defaults to tls if not passed
      # - SMTP_AUTH_REQUIRED=  # defaults to 0 if not passed
      # - SMTP_PASSWORD=      # only used if auth required
      # - SMTP_FQDN=           # used for changing from server's host to a different FQDN
      # - SMTP_DEV_TO=          # used for sending all emails to in development environment
# With FLASK_ENV for dev, use '127.0.0.1:8089:9000'  9000 will be werkzeug in debug mode
    ports: ['9000:9000']
# When FLASK_ENV is commented out to run production, use ['127.0.0.1:8089:80']
# Port 80 is nginx with caching for static files and proxies gunicorn's 9000
#    ports: ['127.0.0.1:8089:80']
# to connect to local files for development
    volumes:
      - ./ps_utils:/app
# uncomment for production to prevent run away logs
    # logging:
    #   options:
    #     max-size: "1000k"
    #     max-file: "10"
    links:
      - db:db
# for docker-bench-security
    cpu_shares: 73
    mem_limit: 512m
    pids_limit: 50
    healthcheck:
      test: ["CMD", "wget", "-O-", "http://localhost:9000"]  # remove ':9000' for production
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: on-failure:5
    privileged: false
    ulimits:
      nproc: 65535
    security_opt:
      - no-new-privileges:true
# for weave network
    # network_mode: "bridge"
    # dns_search:
    #   - weave.local

    # command: flask run  #  to run as flask instead of gunicorn


  db:
    image: percona
    restart: always
    environment:
        - MYSQL_ROOT_PASSWORD=rootpassword
        - MYSQL_USER=youruser
        - MYSQL_PASSWORD=yourpassword
        - MYSQL_DATABASE=ps_utils
# for weave network
    # network_mode: "bridge"
    # dns_search:
    #   - weave.local

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    links:
      - db:db
# for weave network
    # network_mode: "bridge"
    # dns_search:
    #   - weave.local
